method: grid

metric:
  name: val/loss_ckpt
  goal: minimize

parameters:
  set:
    values:
      - data.dataset.degradation.mask_fraction=0.95
      - data.dataset.degradation.mask_fraction=0.96
      - data.dataset.degradation.mask_fraction=0.97
      - data.dataset.degradation.mask_fraction=0.98
      - data.dataset.degradation.mask_fraction=0.99
      - data.dataset.degradation.mask_fraction=0.995

command:
  - /work/envs/depth/bin/python
  - train.py
  - --data-config
  - configs/data_config.yaml
  - --train-config
  - configs/training_config.yaml
  - --model-config
  - configs/model_config.yaml
  - --set
  - data.dataset.conditioning.eo_dropout_prob=0.0
  - --set
  - training.trainer.max_epochs=100
  - --set
  - training.wandb.run_name=null
  - ${args}
